version: "3"
services:
  express:
    build:
      context: .
      dockerfile: docker/Dockerfile.express
    ports:
      - "${EXPRESS_PORT}:3000"
    depends_on:
      - rabbitmq
      - redis
      - elasticsearch
      - logstash
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    networks:
      - shared_network

  rabbitmq:
    build:
      context: .
      dockerfile: docker/Dockerfile.rabbitmq
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    networks:
      - shared_network

  redis:
    build:
      context: .
      dockerfile: docker/Dockerfile.redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - shared_network

  elasticsearch:
    build:
      context: .
      dockerfile: docker/Dockerfile.elastic
    ports:
      - "${ELASTICSEARCH_PORT}:9200"
      - "${ELASTICSEARCH_TRANSPORT_PORT}:9300"
    environment:
      - discovery.type=single-node
    networks:
      - shared_network

  kibana:
    build:
      context: .
      dockerfile: docker/Dockerfile.kibana
    ports:
      - "${KIBANA_PORT}:5601"
    depends_on:
      - elasticsearch
    networks:
      - shared_network

  logstash:
    build:
      context: .
      dockerfile: docker/Dockerfile.logstash
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
    depends_on:
      - elasticsearch
    env_file:
      - .env
    networks:
      - shared_network

  filebeat:
    build:
      context: .
      dockerfile: docker/Dockerfile.filebeat
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./logs:/app/logs:ro
    networks:
      - shared-network
    depends_on:
      - logstash
    env_file:
      - .env

networks:
  shared_network:
    external: true
    driver: bridge
