apiVersion: v1
kind: Service
metadata:
  name: express
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: express
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 8080
